//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoVacancy.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdEstablishmentType
    {
        public int EstablishmentTypeID { get; set; }
        public System.Guid Guid { get; set; }
        public string EstablishmentType { get; set; }
        public string EstablishmentTypeDesc { get; set; }
        public int Active { get; set; }
        public Nullable<System.DateTime> DateDeactivated { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public int Deleted { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public Nullable<int> Year { get; set; }
    }
}
