//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoVacancy.DAL.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NoVacancyEntities : DbContext
    {
        public NoVacancyEntities()
            : base("name=NoVacancyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<mdCountry> mdCountries { get; set; }
        public virtual DbSet<mdEstablishmentType> mdEstablishmentTypes { get; set; }
        public virtual DbSet<trEstablishment> trEstablishments { get; set; }
        public virtual DbSet<trOffer> trOffers { get; set; }
    }
}
