//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoVacancy.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class trOffer
    {
        public int OfferID { get; set; }
        public Nullable<System.Guid> Guid { get; set; }
        public Nullable<int> EstablishmentID { get; set; }
        public Nullable<int> EstablishmentTypeID { get; set; }
        public string Description { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> Currency { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<System.DateTime> DateDeactivated { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public int Deleted { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<int> Year { get; set; }
    }
}
