//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoVacancy.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class trPackage
    {
        public int PackageID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> EstablishmentID { get; set; }
        public Nullable<int> EstablishmentType { get; set; }
        public Nullable<int> PackageType { get; set; }
        public Nullable<int> Denomination { get; set; }
        public Nullable<double> Price { get; set; }
        public int Active { get; set; }
        public Nullable<System.DateTime> DateDeactivated { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public int Deleted { get; set; }
        public Nullable<int> Year { get; set; }
    }
}
